### PR TITLE
Add Permission composing with operators

### PR DESCRIPTION
**Pull request by Fel-o**
Added new feature which allows building new permissions by combining BasePermission classes with bitwise operators. This is inspired by the same feature from DRF permissions.

### CODE REVIEW

**Comment by Fel-o** [comment]
Also created the BasePermission class from which all other permissions inherit. This class defines the general has_permission() method which by default is False. All other specific methods (e.g. has_node_permission()...) call has_permission if they are not overwritten in child classes. This allows to create simpler permissions. As an example see the new overwritten AllowAuthenticated Permission.

**Comment by redzej** [comment]
Hi @Fel-o, thanks for PR! I'll review it over the weekend and if everything is fine, update pypi version.

**Comment by Fel-o** [comment]
Hey @redzej, any updates?

**Review by redzej — APPROVED** [review]

**Comment by redzej** [comment]
@Fel-o looks good!

**Pull request merged**
